### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by raj2261992** [inspectIT/inspectIT-dvdstore-example#4]
Trying to add Yourkit java agent into docker file but its getting failed during build. Link mentioned in docker file ftp://ntftp.novatec-gmbh.de/inspectit/samples/sample-dvdstore/ is not accessible. Do you have any alternative path or Is there any other way we can add external java agent into inspectit docker setup and build the image??

**Comment by ivansenic** [comment]
Hi @raj2261992 ,

This sample application has been deprecated. Please use the [inspectit-labs/spring-petclinic-microservices](https://github.com/inspectit-labs/spring-petclinic-microservices). There is also the docker compose file you can use there.

**Comment by raj2261992** [comment]
Features like slow query search,slow display are not available in spring-petclinic app. Actually we are looking for sample application which we can use across different APM tools in order to see the performance impact and tool overhead  that's why we were trying to use dvdstore.

**Comment by ivansenic** [comment]
Yes, but on the other hand with the DVD Store you only have one JVM. In the Spring one you have more microservices, thus you can check the remote tracing feature. And nowadays as monolith architecture is dying, you would mostly need that. So you should include it in your "review". 

The integrated performance problems in the DVD store like `slow query search` are maybe not of much help, as you are also getting SQLs in the other demo application. I think you should be interested in checking if SQL capturing is possible and how much the overhead is and you should not care if the SQL takes 1ms or 100ms. Should not affect the review imo.

But it's your choice. We will not support DVD store anymore, but you can freely fix any issues on your own.
